"""empty message

Revision ID: 213a4ce02333
Revises: 2829167b2aff
Create Date: 2015-10-16 14:48:47.100041

"""

# revision identifiers, used by Alembic.
revision = '213a4ce02333'
down_revision = '2829167b2aff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('event_url', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('location_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='_event_slug_uc')
    )
    op.create_index('_event_active_startdate_ix', 'event', ['active', 'start_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_event_active_startdate_ix', table_name='event')
    op.drop_table('event')
    ### end Alembic commands ###
