"""empty message

Revision ID: 2829167b2aff
Revises: 4c98d9952b7e
Create Date: 2015-10-14 11:02:23.553489

"""

# revision identifiers, used by Alembic.
revision = '2829167b2aff'
down_revision = '4c98d9952b7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_taken', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='_gi_slug_uc')
    )
    op.create_index('_gi_slug_active_ix', 'gallery_item', ['slug', 'active'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_gi_slug_active_ix', table_name='gallery_item')
    op.drop_table('gallery_item')
    ### end Alembic commands ###
