"""empty message

Revision ID: 4c98d9952b7e
Revises: 10ac6fbf6ec5
Create Date: 2015-10-01 11:15:15.840234

"""

# revision identifiers, used by Alembic.
revision = '4c98d9952b7e'
down_revision = '10ac6fbf6ec5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_text_content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='_stcb_slug_uc')
    )
    op.create_index('_stcb_slug_active_ix', 'short_text_content_block', ['slug', 'active'], unique=False)
    op.create_table('rich_text_content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='_rtcb_slug_uc')
    )
    op.create_index('_rtcb_slug_active_ix', 'rich_text_content_block', ['slug', 'active'], unique=False)
    op.create_table('image_content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='_icb_slug_uc')
    )
    op.create_index('_icb_slug_active_ix', 'image_content_block', ['slug', 'active'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('_icb_slug_active_ix', table_name='image_content_block')
    op.drop_table('image_content_block')
    op.drop_index('_rtcb_slug_active_ix', table_name='rich_text_content_block')
    op.drop_table('rich_text_content_block')
    op.drop_index('_stcb_slug_active_ix', table_name='short_text_content_block')
    op.drop_table('short_text_content_block')
    ### end Alembic commands ###
